development: &development
  adapter: postgresql
  host: localhost
  database: sparkle_web_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: sparkle_web_test
  encoding: unicode